import type { Metadata } from "next";
import "@/styles/_globals.scss";
import BootstrapClient from "@/components/BootstrapClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BootstrapClient/>
        {children}
      </body>
    </html>
  );
}
